# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_cv_fix_effects <- function(t_x, X, Y, main_index, inter_index, x_params_raw, x_params, y_params, all_folds, upper_comp, thresh) {
    .Call('_FRegSigCom_C_cv_fix_effects', PACKAGE = 'FRegSigCom', t_x, X, Y, main_index, inter_index, x_params_raw, x_params, y_params, all_folds, upper_comp, thresh)
}

C_pred_ff_inter <- function(fit_cv, Y_train, X_test, x_params, y_params, y_penalty_inv) {
    .Call('_FRegSigCom_C_pred_ff_inter', PACKAGE = 'FRegSigCom', fit_cv, Y_train, X_test, x_params, y_params, y_penalty_inv)
}

C_stepwise_adaptive <- function(t_x, X, Y, x_params_raw, x_params, y_params, all_folds, upper_comp, thresh) {
    .Call('_FRegSigCom_C_stepwise_adaptive', PACKAGE = 'FRegSigCom', t_x, X, Y, x_params_raw, x_params, y_params, all_folds, upper_comp, thresh)
}

C_find_coef_ff_interaction <- function(fit_cv, X_train, Y_train, x_params, y_params, y_penalty_inv) {
    .Call('_FRegSigCom_C_find_coef_ff_interaction', PACKAGE = 'FRegSigCom', fit_cv, X_train, Y_train, x_params, y_params, y_penalty_inv)
}

