# Simulation functions for pffr

#' Simulate example data for pffr
#'
#' Simulates example data for \code{\link{pffr}} from a variety of terms.
#' Supports both a formula-based interface (recommended) and a legacy
#' scenario-based interface for backward compatibility.
#'
#' **Formula Interface (Recommended):**
#' Specify a pffr-style formula and optional effect specifications:
#' \preformatted{
#' pffr_simulate(Y ~ ff(X1) + xlin + s(xsmoo), n = 100,
#'               effects = list(X1 = "cosine", xlin = "dnorm"))
#' }
#'
#' **Scenario Interface (Deprecated):**
#' Scenario "all" generates data from a complex multivariate model
#' \deqn{Y_i(t) = \mu(t) + \int X_{1i}(s)\beta_1(s,t)ds + xlin \beta_3(t) +
#' f(xte1, xte2) + f(xsmoo, t) + \beta_4 xconst + f(xfactor, t) + \epsilon_i(t)}
#'
#' Scenarios "int", "ff", "lin", "te", "smoo", "const", "factor" generate data
#' from simpler models containing only the respective terms.
#'
#' Sparse/irregular response trajectories can be generated by setting
#' \code{propmissing} > 0.
#'
#' @param formula A formula specifying the model structure (e.g.,
#'   \code{Y ~ ff(X1) + xlin}). If provided, the \code{scenario} argument is
#'   ignored.
#' @param scenario \strong{Deprecated.} Character string or vector specifying
#'   predefined scenarios. Use the \code{formula} argument instead.
#' @param n Number of observations.
#' @param nxgrid Number of evaluation points for functional covariates.
#'   Ignored if \code{xind} is provided.
#' @param nygrid Number of evaluation points for the functional response.
#'   Ignored if \code{yind} is provided.
#' @param yind Numeric vector of evaluation points for the response.
#'   Defaults to \code{seq(0, 1, length.out = nygrid)}.
#' @param xind Numeric vector of evaluation points for functional covariates.
#'   Defaults to \code{seq(0, 1, length.out = nxgrid)}.
#' @param data Optional data frame with pre-generated covariates.
#' @param effects Named list mapping term labels to effect specifications.
#'   Each entry can be a preset name (e.g., "cosine"), a function, or a numeric
#'   value. See Details.
#' @param intercept Intercept specification: preset name ("beta", "constant",
#'   "sine", "zero"), a function of \code{t}, or a numeric value.
#' @param SNR Signal-to-noise ratio: \code{var(eta) / var(epsilon)}.
#' @param family A family object for the response distribution. Defaults to
#'   \code{gaussian()}.
#' @param propmissing Proportion of missing data in the response (0 to 1).
#' @param limits A function defining integration limits for \code{ff()} terms,
#'   e.g., \code{function(s, t) s < t}.
#' @param seed Optional random seed for reproducibility.
#' @param wiggliness Controls smoothness for the "random" preset (default: 1).
#'   Higher values produce more wiggly truth functions. Typical range: 0.001
#'   (very smooth) to 10 (very wiggly).
#' @param k_truth Named list of basis dimensions for random truth generation.
#'   Defaults: \code{list(ff_s = 8, ff_t = 8, smooth_z = 8, smooth_t = 8,
#'   linear = 8, intercept = 8, concurrent = 8)}.
#'
#' @returns A data frame (or list if \code{propmissing > 0}) with simulated
#'   data and attributes:
#'   \describe{
#'     \item{xindex}{Evaluation points for functional covariates}
#'     \item{yindex}{Evaluation points for the response}
#'     \item{truth}{List containing \code{eta} (linear predictor),
#'       \code{etaTerms} (individual term contributions), \code{beta}
#'       (coefficient functions), and \code{epsilon} (noise)}
#'   }
#'
#' @section Effect Presets:
#' For \code{ff()} terms: "cosine", "product", "gaussian", "separable", "historical", "random"
#'
#' For \code{s()} terms: "beta", "dnorm", "sine", "cosine", "polynomial", "step", "random"
#'
#' For \code{c()} terms: "constant", "gaussian_2d", "linear"
#'
#' For intercept: "constant", "beta", "sine", "zero", "random"
#'
#' For linear terms: "dnorm", "sine", "cosine", "constant", "linear", "random"
#'
#' For concurrent terms: "dnorm", "sine", "cosine", "constant", "linear", "random"
#'
#' The "random" preset generates reproducible random truth functions by
#' sampling from P-spline priors. Use \code{wiggliness} to control the
#' smoothness (curvature).
#'
#' @export
#' @importFrom splines spline.des
#' @importFrom stats dnorm rnorm runif dbeta gaussian var as.formula
#'
#' @examples
#' # Formula interface
#' dat <- pffr_simulate(Y ~ ff(X1) + xlin + s(xsmoo), n = 50,
#'                      effects = list(X1 = "cosine", xlin = "dnorm", xsmoo = "sine"))
#'
#' # Legacy scenario interface (deprecated)
#' dat_legacy <- suppressWarnings(pffr_simulate(scenario = "ff", n = 50))
#'
#' # Access true coefficients
#' truth <- attr(dat, "truth")
#' str(truth$beta)
pffr_simulate <- function(
  formula = NULL,
  scenario = NULL,
  n = 100,
  nxgrid = 40,
  nygrid = 60,
  yind = NULL,
  xind = NULL,
  data = NULL,
  effects = list(),
  intercept = "beta",
  SNR = 10,
  family = gaussian(),
  propmissing = 0,
  limits = NULL,
  seed = NULL,
  wiggliness = 1,
  k_truth = list()
) {
  # Set seed if provided
  if (!is.null(seed)) set.seed(seed)

  # Set up grid indices
  if (is.null(yind)) yind <- seq(0, 1, length.out = nygrid)
  if (is.null(xind)) xind <- seq(0, 1, length.out = nxgrid)

  # Determine which interface to use
  if (!is.null(formula)) {
    # New formula interface
    return(pffrSim_formula(
      formula = formula,
      n = n,
      yind = yind,
      xind = xind,
      data = data,
      effects = effects,
      intercept = intercept,
      SNR = SNR,
      family = family,
      propmissing = propmissing,
      limits = limits,
      wiggliness = wiggliness,
      k_truth = k_truth
    ))
  }

  # Legacy scenario interface
  if (is.null(scenario)) {
    scenario <- "all"
  }

  # Issue deprecation warning once per session (not on every call)
  if (is.null(getOption("refund.pffr_simulate.scenario.warned"))) {
    warning(
      "The 'scenario' argument in pffr_simulate() is deprecated.\n",
      "Use the formula interface instead, e.g.:\n",
      "  pffr_simulate(Y ~ ff(X1) + xlin, effects = list(X1 = 'cosine'))",
      call. = FALSE
    )
    options(refund.pffr_simulate.scenario.warned = TRUE)
  }

  # Use legacy implementation for backward compatibility
  pffrSim_legacy(
    scenario = scenario,
    n = n,
    nxgrid = length(xind),
    nygrid = length(yind),
    SNR = SNR,
    propmissing = propmissing,
    limits = limits
  )
}


#' Simulate example data for pffr (deprecated)
#'
#' @description
#' **Deprecated**
#'
#' `pffrSim()` was renamed to [pffr_simulate()] for consistency with the
#' package naming conventions.
#'
#' @inheritParams pffr_simulate
#' @export
#' @keywords internal
pffrSim <- function(
  formula = NULL,
  scenario = NULL,
  n = 100,

  nxgrid = 40,
  nygrid = 60,

  yind = NULL,
  xind = NULL,
  data = NULL,
  effects = list(),
  intercept = "beta",
  SNR = 10,
  family = gaussian(),
  propmissing = 0,
  limits = NULL,
  seed = NULL,
  wiggliness = 1,
  k_truth = list()
) {
  .Deprecated("pffr_simulate")
  pffr_simulate(
    formula = formula,
    scenario = scenario,
    n = n,
    nxgrid = nxgrid,
    nygrid = nygrid,
    yind = yind,
    xind = xind,
    data = data,
    effects = effects,
    intercept = intercept,
    SNR = SNR,
    family = family,
    propmissing = propmissing,
    limits = limits,
    seed = seed,
    wiggliness = wiggliness,
    k_truth = k_truth
  )
}


#' Legacy pffr_simulate implementation
#'
#' Internal function preserving the original pffr_simulate behavior for backward
#' compatibility. This is called when the deprecated \code{scenario} argument
#' is used.
#'
#' @inheritParams pffr_simulate
#' @keywords internal
pffrSim_legacy <- function(
  scenario = "all",
  n = 100,
  nxgrid = 40,
  nygrid = 60,
  SNR = 10,
  propmissing = 0,
  limits = NULL
) {
  mc <- match.call()

  ## generates random functions...
  rf <- function(x = seq(0, 1, length = 100), bs.dim = 7, center = FALSE) {
    nk <- bs.dim - 2
    xu <- max(x)
    xl <- min(x)
    xr <- xu - xl
    xl <- xl - xr * 0.001
    xu <- xu + xr * 0.001
    dx <- (xu - xl) / (nk - 1)
    kn <- seq(xl - dx * 3, xu + dx * 3, length = nk + 4 + 2)
    X <- splines::spline.des(kn, x, 4, x * 0)$design
    drop(X %*% rnorm(bs.dim))
  }

  test1 <- function(s, t) {
    s * cos(pi * abs(s - t)) - 0.19
  }

  s <- seq(0, 1, length = nxgrid)
  t <- seq(0, 1, length = nygrid)

  mu.t <- matrix(1 + dbeta(t, 2, 7), nrow = n, ncol = nygrid, byrow = TRUE)

  data <- list()
  etaTerms <- list()
  etaTerms$int <- mu.t

  # Functional covariates
  data$X1 <- I(t(replicate(n, rf(s))))

  L <- matrix(1 / nxgrid, ncol = nxgrid, nrow = n)
  LX1 <- L * data$X1
  beta1.st <- outer(s, t, test1)
  if (!is.null(limits)) {
    range <- outer(s, t, limits)
    beta1.st <- beta1.st * range
  }
  etaTerms$X1 <- LX1 %*% beta1.st

  # Scalar covariates
  data$xlin <- I(rnorm(n))
  beta.t <- matrix(
    scale(-dnorm(4 * (t - 0.2))),
    nrow = n,
    ncol = nygrid,
    byrow = TRUE
  )
  etaTerms$xlin <- data$xlin * beta.t

  data$xsmoo <- I(rnorm(n))
  etaTerms$xsmoo <- outer(drop(scale(cos(data$xsmoo))), (t - 0.5), "*")

  data$xfactor <- sample(gl(3, n / 3), replace = TRUE)
  etaTerms$xfactor <- 2 *
    as.numeric(data$xfactor) +
    sin(2 * outer(as.numeric(data$xfactor), t))
  if ("2factor" %in% scenario) {
    data$x2factor <- sample(gl(3, n / 3), replace = TRUE)
    etaTerms$x2factor <- 2 *
      as.numeric(data$x2factor) +
      cos(2 * outer(as.numeric(data$x2factor), t))
  }

  data$xte1 <- I(rnorm(n))
  data$xte2 <- I(rnorm(n))
  etaTerms$xte <- matrix(
    drop(scale(-data$xte1 * data$xte2^2)),
    ncol = nygrid,
    nrow = n
  )

  data$xconst <- I(rnorm(n))
  etaTerms$xconst <- matrix(2 * data$xconst, ncol = nygrid, nrow = n)

  if (length(scenario) == 1) {
    eta <- mu.t +
      switch(
        scenario,
        "int" = 0,
        "all" = Reduce("+", etaTerms),
        "ff" = etaTerms$X1,
        "lin" = etaTerms$xlin,
        "smoo" = etaTerms$xsmoo,
        "te" = etaTerms$xte,
        "const" = etaTerms$xconst,
        "factor" = etaTerms$xfactor
      )
  } else {
    stopifnot(all(
      scenario %in%
        c("int", "ff", "lin", "smoo", "te", "const", "factor", "2factor")
    ))
    eta <- 0 * mu.t
    if ("int" %in% scenario) eta <- eta + mu.t
    if ("ff" %in% scenario) eta <- eta + etaTerms$X1
    if ("lin" %in% scenario) eta <- eta + etaTerms$xlin
    if ("smoo" %in% scenario) eta <- eta + etaTerms$xsmoo
    if ("te" %in% scenario) eta <- eta + etaTerms$xte
    if ("const" %in% scenario) eta <- eta + etaTerms$xconst
    if ("factor" %in% scenario) eta <- eta + etaTerms$xfactor
    if ("2factor" %in% scenario) eta <- eta + etaTerms$x2factor
  }

  eps <- sd(as.vector(eta)) /
    sqrt(SNR) *
    matrix(scale(rnorm(n * nygrid)), nrow = n)
  data$Y <- I(eta + eps)

  if (propmissing == 0) {
    return(structure(
      as.data.frame(data, row.names = 1:n),
      xindex = s,
      yindex = t,
      truth = list(eta = eta, etaTerms = etaTerms),
      call = mc
    ))
  } else {
    missing <- sample(c(
      rep(TRUE, propmissing * n * nygrid),
      rep(FALSE, n * nygrid - propmissing * n * nygrid)
    ))
    data <- as.data.frame(data, row.names = 1:n)

    ydata <- data.frame(
      .obs = rep(1:n, each = nygrid)[!missing],
      .index = rep(t, times = n)[!missing],
      .value = as.vector(t(data$Y))[!missing]
    )

    return(structure(
      list(data = data, ydata = ydata),
      xindex = s,
      yindex = t,
      truth = list(eta = eta, etaTerms = etaTerms),
      call = mc
    ))
  }
}
